name: restockr
description: Inventory restocking companion app.
version: 1.0.0+1
environment: 
  sdk: ^3.6.0
dependencies: 
  flutter:   # 🚨 CRITICAL: Required for every Flutter project - DO NOT REMOVE
    sdk: flutter # 🚨 CRITICAL: Required for every Flutter project - DO NOT REMOVE
  flutter_localizations: 
    sdk: flutter
  flutter_svg: ^2.0.12
  cached_network_image: ^3.4.1
  shared_preferences: ^2.3.3
  connectivity_plus: ^6.1.0
  gradient_borders: ^1.0.2
  flutter_riverpod: ^2.5.1
  equatable: ^2.0.5
  universal_html: ^2.2.4
  dio: ^5.4.0
  flutter_secure_storage: ^9.0.0
  jwt_decoder: ^2.0.1
  url_launcher: ^6.3.1
  flutter_web_auth_2: ^3.1.2
  intl: ^0.20.2
  socket_io_client: ^3.1.2  # Upgraded for better iOS Simulator support
  web_socket_channel: ^2.4.0  # Backup alternative
  cookie_jar: ^4.0.8  # Cookie management for WebSocket sessions
  dio_cookie_manager: ^3.1.1  # Dio interceptor for cookie persistence
dev_dependencies:
  flutter_test:    # 🚨 CRITICAL: Required for Flutter project testing - DO NOT REMOVE
    sdk: flutter    # 🚨 CRITICAL: Required for Flutter project testing - DO NOT REMOVE
  flutter_lints: ^3.0.1
  mockito: ^5.4.4
  build_runner: ^2.4.13
flutter:
  uses-material-design: true # 🚨 CRITICAL: Required for Material icon font - DO NOT REMOVE
  assets:
    - env.json
    - assets/
    - assets/images/
  fonts: 
    - family: Inter
      fonts: 
        - asset: assets/fonts/InterSemiBold.ttf
          weight: 600
        - asset: assets/fonts/InterMedium.ttf
          weight: 500
        - asset: assets/fonts/InterBold.ttf
          weight: 700
        - asset: assets/fonts/InterRegular.ttf
          weight: 400

  # 🚨 CRITICAL ASSET MANAGEMENT RULES:
  # - DO NOT ADD NEW ASSET DIRECTORIES (assets/svg/, assets/icons/, etc.)
  # - ONLY USE EXISTING AND ITEMS AVAILABLE IN THE DIRECTORIES LISTED ABOVE (assets/, assets/images/)

  # 🚨 CRITICAL FONTS RULE:
  # - DO NOT ADD NEW LOCAL FONTS TO assets/fonts/ 
  # - ONLY USE EXISTING LOCAL FONTS FROM assets/fonts/
